# Generated by Django 6.0.4 on 2026-04-25 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Name of the Event', max_length=200)),
                ('event_venue', models.CharField(help_text='Location or place for event', max_length=200)),
                ('event_date', models.DateTimeField(help_text='Date for the event')),
                ('event_capacity', models.IntegerField(help_text='How many people would might attend')),
                ('event_type', models.CharField(help_text='What type of event this would be', max_length=200)),
                ('event_details', models.TextField(help_text='Add details for event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
